version: "3.9"

services:
  bot:
    build:
      context: .
      dockerfile: docker/bot.Dockerfile
    env_file: .env
    depends_on: [redis]

  api:
    build:
      context: .
      dockerfile: docker/api.Dockerfile
    command: uvicorn api.main:app --host 0.0.0.0 --port 8000
    env_file: .env
    depends_on: [db]

  worker:
    build:
      context: .
      dockerfile: docker/worker.Dockerfile
    env_file: .env
    depends_on: [redis]

  db:
    image: postgres:15
    restart: unless-stopped
    environment:
      POSTGRES_USER: diy
      POSTGRES_PASSWORD: diy
      POSTGRES_DB: diy

  redis:
    image: redis:7-alpine
    restart: unless-stopped
